/**
 * Patch applier — writes approved patches to the learned behaviors file
 * and applies configuration deltas for tool-policy and model-routing patches.
 *
 * The learned behaviors file lives at `~/.agents/agentsy/learned-behaviors.md`
 * and is auto-created if it does not exist. Patches with confidence >= 0.9
 * are auto-applied; patches with confidence < 0.9 require user approval.
 *
 * @module learning/patch-applier
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { resolve } from 'node:path';
import type { PromptPatch } from './types.js';

// =============================================================================
// Constants
// =============================================================================

/**
 * Path to the learned behaviors markdown file.
 */
const LEARNED_BEHAVIORS_PATH = resolve(homedir(), '.agents', 'agentsy', 'learned-behaviors.md');

/**
 * Auto-apply threshold — patches with confidence >= this are applied
 * without user approval.
 */
const AUTO_APPLY_THRESHOLD = 0.9;

// =============================================================================
// Types
// =============================================================================

/**
 * Result of applying a patch.
 */
export interface ApplyPatchResult {
  /** Whether the patch was applied. */
  applied: boolean;
  /** Whether user approval was granted (false if not needed). */
  approvalGranted: boolean;
  /** Path to the file that was written/modified. */
  filePath: string;
  /** The patch that was applied (with updated status). */
  patch: PromptPatch;
  /** Whether user approval was required. */
  requiredApproval: boolean;
}

// =============================================================================
// Public API
// =============================================================================

/**
 * Apply an approved patch to the learned behaviors file and any
 * configuration deltas.
 *
 * Patches with confidence >= 0.9 are auto-applied. Patches below
 * that threshold require explicit user approval (caller must set
 * `approved` on the patch).
 *
 * @param patch - The patch to apply (must have status 'approved').
 * @returns The apply result with updated patch.
 */
export function applyPatch(patch: PromptPatch, options?: { behaviorsPath?: string }): ApplyPatchResult {
  const behaviorsPath = options?.behaviorsPath ?? LEARNED_BEHAVIORS_PATH;
  const requiresApproval = patch.confidence < AUTO_APPLY_THRESHOLD;
  const isApproved = patch.status === 'approved';

  if (isApproved) {
    // Write the behaviors file
    ensureTargetDirectory(behaviorsPath);
    appendToBehaviorsFile(behaviorsPath, patch);

    // Apply target-specific deltas
    if (patch.target === 'model-routing') {
      applyModelRoutingPatch(patch);
    }

    const appliedPatch: PromptPatch = {
      ...patch,
      status: 'applied',
      appliedAt: new Date()
    };

    return {
      patch: appliedPatch,
      applied: true,
      requiredApproval: requiresApproval,
      approvalGranted: true,
      filePath: behaviorsPath
    };
  }

  // Patch is not approved — not applied
  return {
    patch,
    applied: false,
    requiredApproval: requiresApproval,
    approvalGranted: false,
    filePath: behaviorsPath
  };
}

/**
 * Get the path to the learned behaviors file.
 */
export function getBehaviorsFilePath(): string {
  return LEARNED_BEHAVIORS_PATH;
}

// =============================================================================
// Internal helpers
// =============================================================================

/**
 * Ensure the target directory exists for a given file path.
 */
function ensureTargetDirectory(filePath: string): void {
  const dir = resolve(filePath, '..');
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

/**
 * Append a patch to the learned behaviors markdown file.
 *
 * If the file does not exist, it is created with a header.
 */
function appendToBehaviorsFile(filePath: string, patch: PromptPatch): void {
  const header =
    '# Learned Behaviors\n\n> Auto-generated by @agentsy/tokenomics learning loop.\n> These patches are applied based on recurring frustration patterns.\n\n';

  let existing = '';
  if (existsSync(filePath)) {
    existing = readFileSync(filePath, 'utf-8');
  }

  const entry = formatPatchEntry(patch);
  const content = existing.length > 0 ? `${existing}\n${entry}` : `${header}${entry}`;

  writeFileSync(filePath, content, 'utf-8');
}

/**
 * Format a patch as a markdown entry suitable for the behaviors file.
 */
function formatPatchEntry(patch: PromptPatch): string {
  const lines: string[] = [];
  lines.push(`## Patch: ${patch.id}`);
  lines.push('');
  lines.push(`- **Failure Mode**: ${patch.failureModeId}`);
  lines.push(`- **Target**: ${patch.target}`);
  lines.push(`- **Target Path**: ${patch.targetPath}`);
  lines.push(`- **Section**: ${patch.section}`);
  lines.push(`- **Confidence**: ${(patch.confidence * 100).toFixed(0)}%`);
  lines.push(`- **Created**: ${patch.createdAt.toISOString()}`);
  lines.push(`- **Applied**: ${patch.appliedAt?.toISOString() ?? 'N/A'}`);
  lines.push('');
  lines.push('### Content');
  lines.push('');
  lines.push('```');
  lines.push(patch.content);
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

// =============================================================================
// Model routing patch support
// =============================================================================

/**
 * Model routing patch entry type for the routing overrides file.
 */
interface RoutingOverrideEntry {
  appliedAt: string;
  confidence: number;
  content: string;
  failureModeId: string;
  patchId: string;
  section: string;
  targetPath: string;
}

/**
 * Apply a model-routing patch by writing to the routing overrides file.
 *
 * The routing overrides file lives at `~/.agents/agentsy/routing-overrides.json`
 * and is read by the headroom provider to adjust routing weights.
 */
function applyModelRoutingPatch(patch: PromptPatch): void {
  const routingPath = resolve(homedir(), '.agents', 'agentsy', 'routing-overrides.json');
  ensureTargetDirectory(routingPath);

  let overrides: { patches: RoutingOverrideEntry[] } = { patches: [] };
  if (existsSync(routingPath)) {
    try {
      overrides = JSON.parse(readFileSync(routingPath, 'utf-8'));
    } catch {
      // Corrupted file — start fresh
    }
  }

  overrides.patches.push({
    failureModeId: patch.failureModeId,
    patchId: patch.id,
    targetPath: patch.targetPath,
    section: patch.section,
    content: patch.content,
    confidence: patch.confidence,
    appliedAt: new Date().toISOString()
  });

  writeFileSync(routingPath, JSON.stringify(overrides, null, 2), 'utf-8');
}
